import type { AgentTemplateSeed, CatalogSourceSeed, PlanPackageSeed, TemplateTaskSeed } from "./types";

const techNewsSources: CatalogSourceSeed[] = [
  { key: "webrazzi", label: "Webrazzi", description: "Turkiye teknoloji ve startup haberleri.", defaultSelected: true },
  { key: "shiftdelete", label: "ShiftDelete", description: "Turkiye teknoloji ve cihaz guncellemeleri.", defaultSelected: true },
  { key: "log", label: "LOG", description: "Turkiye teknoloji ve yasam haberleri.", defaultSelected: true },
  { key: "donanimhaber", label: "DonanimHaber", description: "Turkiye donanim ve teknoloji haberleri.", defaultSelected: true },
  { key: "techcrunch", label: "TechCrunch", description: "Global startup, AI ve urun haberleri.", defaultSelected: true },
  { key: "theverge", label: "The Verge", description: "Global urun, platform ve teknoloji gundemi.", defaultSelected: true },
  { key: "wired", label: "Wired", description: "Teknoloji kultur ve strateji haberleri.", defaultSelected: true },
  { key: "arstechnica", label: "Ars Technica", description: "Derin teknik haberler ve analizler.", defaultSelected: true },
  { key: "venturebeat", label: "VentureBeat", description: "AI, enterprise ve pazar haberleri.", defaultSelected: true },
  { key: "engadget", label: "Engadget", description: "Urun ve platform haberleri.", defaultSelected: true },
  { key: "zdnet", label: "ZDNet", description: "Kurumsal teknoloji ve BT haberleri.", defaultSelected: true },
  { key: "cio", label: "CIO", description: "CIO gundemi ve enterprise teknoloji icerikleri." },
  { key: "cnbc-tech", label: "CNBC Tech", description: "Pazar etkili buyuk teknoloji haberleri." },
  { key: "reuters-tech", label: "Reuters Tech", description: "Dogrulanmis global teknoloji haberleri.", defaultSelected: true },
  { key: "bloomberg-tech", label: "Bloomberg Tech", description: "Global teknoloji ve yonetici hareketleri." },
  { key: "information", label: "The Information", description: "Sirket ve urun strateji haberleri." },
  { key: "mit-tech", label: "MIT Technology Review", description: "Arastirma ve trend odakli teknoloji icerikleri." },
  { key: "mashable", label: "Mashable", description: "Dijital kultur ve internet trendleri." },
  { key: "9to5google", label: "9to5Google", description: "Google ekosistem haberleri." },
  { key: "9to5mac", label: "9to5Mac", description: "Apple ekosistem haberleri." },
  { key: "androidpolice", label: "Android Police", description: "Android ve mobil haberler." },
  { key: "macrumors", label: "MacRumors", description: "Apple urun ve servis guncellemeleri." },
  { key: "openai-blog", label: "OpenAI Blog", description: "OpenAI resmi duyurulari." },
  { key: "google-blog", label: "Google Blog", description: "Google resmi urun ve sirket duyurulari." },
  { key: "microsoft-blog", label: "Microsoft Blog", description: "Microsoft resmi urun ve sirket duyurulari." },
  { key: "meta-newsroom", label: "Meta Newsroom", description: "Meta resmi duyuru ve guncellemeleri." },
  { key: "aws-blog", label: "AWS Blog", description: "AWS urun ve servis guncellemeleri." },
  { key: "anthropic-news", label: "Anthropic News", description: "Anthropic resmi aciklamalari." },
  { key: "huggingface-blog", label: "Hugging Face Blog", description: "Acik kaynak AI urun ve topluluk haberleri." },
  { key: "producthunt", label: "Product Hunt", description: "Yeni urun cikislari ve viral teknoloji urunleri." },
];

const leadOutputFields = {
  findingKind: "LEAD" as const,
  requiredMetadataFields: [
    "firmaAdi",
    "firmaSektoru",
    "adres",
    "telefon",
    "eposta",
    "faaliyetOzeti",
    "platform",
    "kaynakLink",
  ],
  metadataLabels: {
    firmaAdi: "Firma Adi",
    firmaSektoru: "Firma Sektoru",
    adres: "Adres",
    telefon: "Telefon",
    eposta: "E-posta",
    faaliyetOzeti: "Faaliyet Ozeti",
    platform: "Kaynak Platform",
    kaynakLink: "Kaynak Link",
  },
};

const leadTasks: TemplateTaskSeed[] = [
  {
    key: "lead-list",
    name: "Firma listesini cikar",
    category: "lead",
    description: "Kriterlere uyan firma listesini cikartir.",
    instruction: "Kaynaklardaki uygun firma ve uzman profillerini listele; tekrar eden kayitlari birlestir.",
    defaultSelected: true,
  },
  {
    key: "contact-enrichment",
    name: "Iletisim bilgilerini zenginlastir",
    category: "lead",
    description: "Telefon, e-posta ve adres bilgilerini dogrular.",
    instruction: "Bulabildigin telefon, e-posta ve adres bilgisini metadata alanlarinda doldur.",
    defaultSelected: true,
  },
  {
    key: "activity-summary",
    name: "Faaliyet alanini ozetle",
    category: "lead",
    description: "Firmanin ne is yaptigini kisa ve net yazar.",
    instruction: "Her firma icin faaliyet alanini bir iki cumlede ozetle.",
    defaultSelected: true,
  },
];

export const PACKAGE_SEEDS: PlanPackageSeed[] = [
  {
    key: "FREE",
    name: "Free Forever",
    monthlyPrice: 0,
    currency: "USD",
    activeAgentLimit: 1,
    allowsCustomAgentBuilder: false,
    sortOrder: 0,
  },
  {
    key: "BASIC",
    name: "Basic",
    monthlyPrice: 4900,
    currency: "USD",
    activeAgentLimit: 3,
    allowsCustomAgentBuilder: false,
    sortOrder: 1,
  },
  {
    key: "PRO",
    name: "Pro",
    monthlyPrice: 14900,
    currency: "USD",
    activeAgentLimit: 10,
    allowsCustomAgentBuilder: false,
    sortOrder: 2,
  },
  {
    key: "PREMIUM",
    name: "Premium",
    monthlyPrice: 39900,
    currency: "USD",
    activeAgentLimit: 9999,
    allowsCustomAgentBuilder: true,
    sortOrder: 3,
  },
];

export const AGENT_TEMPLATE_SEEDS: AgentTemplateSeed[] = [
  {
    id: "lead-research-tr",
    name: "Lead Arastirma Ajani TR",
    category: "lead",
    description: "Google Maps, LinkedIn ve Sari Sayfalar benzeri kaynaklarda Turkiye odakli potansiyel musteri arastirmasi yapar.",
    defaultPrompt:
      "Turkiye odakli lead arastirmasi yap. Secilen platformlarda kriterlere uyan firmalari bul, tekrarlari ayikla ve her bulgu icin zorunlu metadata alanlarini eksiksiz doldur.",
    defaultQueries: [
      "Turkiye B2B firma listesi Google Maps LinkedIn son 7 gun",
      "Turkiye kurumsal hizmetler firma rehberi son 7 gun",
      "Turkiye teknoloji hizmetleri potansiyel musteri LinkedIn Google Maps",
    ],
    defaultTasks: leadTasks,
    taskBlueprints: leadTasks,
    defaultSchedule: {
      hour: 9,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 5,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 14,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: [
      { key: "google-maps", label: "Google Maps", description: "Lokasyon ve isletme odakli arama.", queryHint: "Google Maps", defaultSelected: true },
      { key: "linkedin", label: "LinkedIn", description: "Sirket ve profesyonel profil aramasi.", queryHint: "LinkedIn", defaultSelected: true },
      { key: "sarisayfalar", label: "Sari Sayfalar", description: "Firma rehberi ve iletisim kaynaklari.", queryHint: "Sari Sayfalar", defaultSelected: true },
    ],
    configSchema: [
      {
        key: "focusKeywords",
        label: "Arastirma konusu",
        type: "textarea",
        placeholder: "Her satira bir arastirma konusu yaz. Ornek: SaaS firmalari",
        helpText: "Ajanin odaklanacagi sektor veya hizmet basliklari.",
        required: true,
      },
      {
        key: "customSourceUrls",
        label: "Ek kaynak URL'leri",
        type: "textarea",
        placeholder: "https://...",
        helpText: "Varsa her satira bir ek URL yaz.",
      },
    ],
    outputSchema: leadOutputFields,
    visibilityPackageKey: "BASIC",
  },
  {
    id: "lead-research-global",
    name: "Lead Arastirma Ajani Global",
    category: "lead",
    description: "Google Maps, LinkedIn, Upwork, Fiverr ve Freelancer benzeri kaynaklarda global lead arastirmasi yapar.",
    defaultPrompt:
      "Global lead arastirmasi yap. Secilen platformlarda kriterlere uyan firmalari veya ekipleri bul, iletisim bilgilerini cikar ve her kayitta zorunlu metadata alanlarini doldur.",
    defaultQueries: [
      "global B2B company leads LinkedIn Upwork Fiverr Freelancer",
      "software agency leads worldwide Google Maps LinkedIn",
      "global service providers contact list last 7 days",
    ],
    defaultTasks: leadTasks,
    taskBlueprints: leadTasks,
    defaultSchedule: {
      hour: 10,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 5,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 14,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: [
      { key: "google-maps", label: "Google Maps", description: "Lokasyon ve isletme odakli arama.", queryHint: "Google Maps", defaultSelected: true },
      { key: "linkedin", label: "LinkedIn", description: "Sirket ve profesyonel profil aramasi.", queryHint: "LinkedIn", defaultSelected: true },
      { key: "upwork", label: "Upwork", description: "Freelance ekip ve sirket aramasi.", queryHint: "Upwork", defaultSelected: true },
      { key: "fiverr", label: "Fiverr", description: "Servis saglayici aramasi.", queryHint: "Fiverr", defaultSelected: true },
      { key: "freelancer", label: "Freelancer", description: "Freelancer ve ekip aramasi.", queryHint: "Freelancer", defaultSelected: true },
    ],
    configSchema: [
      {
        key: "focusKeywords",
        label: "Arastirma konusu",
        type: "textarea",
        placeholder: "Her satira bir arastirma konusu yaz. Ornek: fintech development agencies",
        helpText: "Ajanin arayacagi global sektor ve hizmet basliklari.",
        required: true,
      },
      {
        key: "customSourceUrls",
        label: "Ek kaynak URL'leri",
        type: "textarea",
        placeholder: "https://...",
        helpText: "Varsa her satira bir ek URL yaz.",
      },
    ],
    outputSchema: leadOutputFields,
    visibilityPackageKey: "PRO",
  },
  {
    id: "general-news-research",
    name: "Genel Haber Arastirma Ajani",
    category: "news",
    description: "Turkiye ve global teknoloji gundemini secilen kaynaklardan derleyip yonetici ozeti haline getirir.",
    defaultPrompt:
      "Secilen haber kaynaklarindaki son 7 gunluk teknoloji gundemini ozetle. Turkce ve yabanci kaynaklari birlikte kullan, tekrar eden haberleri ayikla ve one cikan gelismeleri raporla.",
    defaultQueries: [
      "technology news AI product launch executive change last 7 days",
      "global technology headlines startups enterprise AI last 7 days",
      "Turkiye teknoloji haberleri yapay zeka yazilim son 7 gun",
    ],
    defaultTasks: [
      {
        key: "headline-summary",
        name: "Haber ozeti cikar",
        category: "news",
        description: "One cikan haberleri kisa ozetler halinde toplar.",
        instruction: "Her haberi karar verici ozeti gibi kisa ve net yaz.",
        defaultSelected: true,
      },
      {
        key: "business-impact",
        name: "Is etkisini belirt",
        category: "news",
        description: "Haberi risk veya firsat baglaminda yorumlar.",
        instruction: "Her haber icin is etkisini, firsat veya risk acisindan acikla.",
        defaultSelected: true,
      },
      {
        key: "source-priority",
        name: "Kaynak onceligi ver",
        category: "news",
        description: "Kaynak kalitesine gore one cikanlari ayirir.",
        instruction: "Yuksek etkili ve dogrulanmis kaynaklari daha yuksek oncelikla ver.",
      },
    ],
    taskBlueprints: [
      {
        key: "headline-summary",
        name: "Haber ozeti cikar",
        category: "news",
        description: "One cikan haberleri kisa ozetler halinde toplar.",
        instruction: "Her haberi karar verici ozeti gibi kisa ve net yaz.",
        defaultSelected: true,
      },
      {
        key: "business-impact",
        name: "Is etkisini belirt",
        category: "news",
        description: "Haberi risk veya firsat baglaminda yorumlar.",
        instruction: "Her haber icin is etkisini, firsat veya risk acisindan acikla.",
        defaultSelected: true,
      },
      {
        key: "source-priority",
        name: "Kaynak onceligi ver",
        category: "news",
        description: "Kaynak kalitesine gore one cikanlari ayirir.",
        instruction: "Yuksek etkili ve dogrulanmis kaynaklari daha yuksek oncelikla ver.",
      },
    ],
    defaultSchedule: {
      hour: 8,
      minute: 30,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 7,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: techNewsSources,
    configSchema: [
      {
        key: "focusKeywords",
        label: "Odak basliklari",
        type: "textarea",
        placeholder: "Ornek: AI, enterprise software, cloud",
        helpText: "Istersen haber taramasini bu basliklara odaklayabilirsin.",
      },
      {
        key: "customSourceUrls",
        label: "Musteri kaynak URL'leri",
        type: "textarea",
        placeholder: "https://...",
        helpText: "Her satira bir ek haber kaynagi yaz.",
      },
    ],
    outputSchema: {
      findingKind: "NEWS",
    },
    visibilityPackageKey: "FREE",
  },
  {
    id: "crypto-research",
    name: "Kripto Arastirma Ajani",
    category: "crypto",
    description: "Kripto borsalari, haber kaynaklari, bloggerlar, X ve Reddit sinyallerini arastirir.",
    defaultPrompt:
      "Secilen kripto kaynaklarinda son 7 gunun haberlerini, piyasa sinyallerini ve topluluk gundemini topla. Yatirim tavsiyesi verme; trend, risk ve dikkat noktalarini ozetle.",
    defaultQueries: [
      "crypto exchange news whale transfer reddit sentiment last 7 days",
      "bitcoin ethereum market signal twitter reddit last 7 days",
      "crypto market moving news bloggers exchange announcements last 7 days",
    ],
    defaultTasks: [
      {
        key: "market-signals",
        name: "Piyasa sinyali topla",
        category: "crypto",
        description: "Yukselis veya dusus sinyallerini cikarir.",
        instruction: "Fiyat, hacim, haber ve topluluk verisinden sinyal ozetleri cikar.",
        defaultSelected: true,
      },
      {
        key: "news-wrap",
        name: "Kripto haber ozeti",
        category: "crypto",
        description: "One cikan haberleri ozetler.",
        instruction: "Borsa, token ve reguasyon haberlerini kisaca ozetle.",
        defaultSelected: true,
      },
      {
        key: "community-watch",
        name: "Topluluk nabzi cikar",
        category: "crypto",
        description: "Reddit ve X gundemini ayiklar.",
        instruction: "Toplulukta en cok tekrar eden basliklari ve duygu yonunu belirt.",
      },
    ],
    taskBlueprints: [
      {
        key: "market-signals",
        name: "Piyasa sinyali topla",
        category: "crypto",
        description: "Yukselis veya dusus sinyallerini cikarir.",
        instruction: "Fiyat, hacim, haber ve topluluk verisinden sinyal ozetleri cikar.",
        defaultSelected: true,
      },
      {
        key: "news-wrap",
        name: "Kripto haber ozeti",
        category: "crypto",
        description: "One cikan haberleri ozetler.",
        instruction: "Borsa, token ve reguasyon haberlerini kisaca ozetle.",
        defaultSelected: true,
      },
      {
        key: "community-watch",
        name: "Topluluk nabzi cikar",
        category: "crypto",
        description: "Reddit ve X gundemini ayiklar.",
        instruction: "Toplulukta en cok tekrar eden basliklari ve duygu yonunu belirt.",
      },
    ],
    defaultSchedule: {
      hour: 7,
      minute: 15,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 7,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: [
      { key: "exchange-news", label: "Kripto Borsa Haberleri", description: "Binance, OKX ve benzeri borsa haberleri.", defaultSelected: true },
      { key: "bloggers", label: "Kripto Bloggerlari", description: "Uzman yorumlari ve piyasa icerikleri.", defaultSelected: true },
      { key: "tweets", label: "X / Tweet Akisi", description: "Piyasayi etkileyen paylasimlar ve duyurular.", defaultSelected: true },
      { key: "reddit", label: "Reddit Basliklari", description: "Topluluk tartismalari ve duygu yonu.", defaultSelected: true },
      { key: "exchange-announcements", label: "Borsa Duyurulari", description: "Listeleme, delist ve teknik duyurular.", defaultSelected: true },
    ],
    configSchema: [
      {
        key: "focusKeywords",
        label: "Izlenecek coin veya tema",
        type: "textarea",
        placeholder: "Ornek: BTC, ETH, memecoin, layer 2",
        helpText: "Her satira bir coin, tema veya odak konu yaz.",
      },
      {
        key: "customSourceUrls",
        label: "Ek kaynak URL'leri",
        type: "textarea",
        placeholder: "https://...",
        helpText: "Her satira bir ek kaynak yaz.",
      },
    ],
    outputSchema: {
      findingKind: "MARKET_SIGNAL",
    },
    visibilityPackageKey: "PRO",
  },
  {
    id: "it-research",
    name: "IT Arastirma Ajani",
    category: "it",
    description: "Global IT gundemini; yonetici degisiklikleri, urunler, servisler ve teknoloji trendleriyle birlikte raporlar.",
    defaultPrompt:
      "Secilen IT odak alanlarinda dunya genelindeki son 7 gunluk gelismeleri tara. Ust duzey atamalar, istifalar, urun lansmanlari, servis duyurulari ve stratejik planlari ayikla.",
    defaultQueries: [
      "IT executive changes product launch enterprise services AI hardware software last 7 days",
      "CIO CTO appointment resignation enterprise technology last 7 days",
      "global IT services software hardware AI strategy news last 7 days",
    ],
    defaultTasks: [
      {
        key: "exec-moves",
        name: "Ust duzey hareketleri cikar",
        category: "it",
        description: "Atama, istifa ve gorev degisikliklerini toplar.",
        instruction: "Sirketlerdeki yonetici hareketlerini sirket ve rol bazinda listele.",
        defaultSelected: true,
      },
      {
        key: "product-news",
        name: "Urun ve servis haberlerini cikar",
        category: "it",
        description: "Yazilim, donanim ve servis haberlerini derler.",
        instruction: "Dikkat ceken urun, servis ve platform gelismelerini ozetle.",
        defaultSelected: true,
      },
      {
        key: "strategy-signals",
        name: "Stratejik sinyalleri yaz",
        category: "it",
        description: "Gelecek planlari ve AI odakli adimlari ayiklar.",
        instruction: "AI, kripto, VR, donanim ve yazilim tarafindaki stratejik hamleleri isaretle.",
      },
    ],
    taskBlueprints: [
      {
        key: "exec-moves",
        name: "Ust duzey hareketleri cikar",
        category: "it",
        description: "Atama, istifa ve gorev degisikliklerini toplar.",
        instruction: "Sirketlerdeki yonetici hareketlerini sirket ve rol bazinda listele.",
        defaultSelected: true,
      },
      {
        key: "product-news",
        name: "Urun ve servis haberlerini cikar",
        category: "it",
        description: "Yazilim, donanim ve servis haberlerini derler.",
        instruction: "Dikkat ceken urun, servis ve platform gelismelerini ozetle.",
        defaultSelected: true,
      },
      {
        key: "strategy-signals",
        name: "Stratejik sinyalleri yaz",
        category: "it",
        description: "Gelecek planlari ve AI odakli adimlari ayiklar.",
        instruction: "AI, kripto, VR, donanim ve yazilim tarafindaki stratejik hamleleri isaretle.",
      },
    ],
    defaultSchedule: {
      hour: 9,
      minute: 30,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 5,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: techNewsSources,
    configSchema: [
      {
        key: "focusKeywords",
        label: "IT odak alanlari",
        type: "textarea",
        placeholder: "Ornek: AI, crypto, VR, hardware, software services",
        helpText: "Her satira bir odak basligi yaz.",
      },
      {
        key: "customSourceUrls",
        label: "Ek kaynak URL'leri",
        type: "textarea",
        placeholder: "https://...",
        helpText: "Her satira bir ek IT kaynagi yaz.",
      },
    ],
    outputSchema: {
      findingKind: "NEWS",
    },
    visibilityPackageKey: "PRO",
  },
  {
    id: "finance-research",
    name: "Finans Arastirma Ajani",
    category: "finance",
    description: "Finans ve ekonomi gundemini, tahminleri ve yonlendirici icgoru basliklarini raporlar.",
    defaultPrompt:
      "Secilen finans kaynaklarindaki son 7 gunluk ekonomi ve piyasa gelismelerini topla. Yatirim tavsiyesi verme; egilimleri, tahminleri, riskleri ve yol gosterici icgoruleri ozetle.",
    defaultQueries: [
      "finance economy market outlook inflation rates investment forecast last 7 days",
      "macro economy market signal global finance last 7 days",
      "Turkiye ekonomi finans yatirim beklentisi son 7 gun",
    ],
    defaultTasks: [
      {
        key: "macro-summary",
        name: "Makro gundem ozeti",
        category: "finance",
        description: "Makro ekonomi basliklarini ozetler.",
        instruction: "Faiz, enflasyon, buyume ve benzeri makro basliklari karar verici diliyle ozetle.",
        defaultSelected: true,
      },
      {
        key: "market-outlook",
        name: "Piyasa gorunumu yaz",
        category: "finance",
        description: "One cikan piyasa beklentilerini yorumlar.",
        instruction: "One cikan tahminleri, beklentileri ve riskleri sirala.",
        defaultSelected: true,
      },
      {
        key: "guidance-notes",
        name: "Yol gosterici notlar cikar",
        category: "finance",
        description: "Karar destekli notlar uretir.",
        instruction: "Yatirim dusunen kullanicilar icin yonlendirici ama tarafsiz notlar ekle.",
      },
    ],
    taskBlueprints: [
      {
        key: "macro-summary",
        name: "Makro gundem ozeti",
        category: "finance",
        description: "Makro ekonomi basliklarini ozetler.",
        instruction: "Faiz, enflasyon, buyume ve benzeri makro basliklari karar verici diliyle ozetle.",
        defaultSelected: true,
      },
      {
        key: "market-outlook",
        name: "Piyasa gorunumu yaz",
        category: "finance",
        description: "One cikan piyasa beklentilerini yorumlar.",
        instruction: "One cikan tahminleri, beklentileri ve riskleri sirala.",
        defaultSelected: true,
      },
      {
        key: "guidance-notes",
        name: "Yol gosterici notlar cikar",
        category: "finance",
        description: "Karar destekli notlar uretir.",
        instruction: "Yatirim dusunen kullanicilar icin yonlendirici ama tarafsiz notlar ekle.",
      },
    ],
    defaultSchedule: {
      hour: 8,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 7,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: [
      { key: "reuters-finance", label: "Reuters Finance", description: "Global finans haberleri.", defaultSelected: true },
      { key: "bloomberg-markets", label: "Bloomberg Markets", description: "Piyasa ve ekonomi haberleri.", defaultSelected: true },
      { key: "wsj-markets", label: "WSJ Markets", description: "Piyasa ve sirket gundemi." },
      { key: "financial-times", label: "Financial Times", description: "Kuresel finans ve ekonomi haberleri.", defaultSelected: true },
      { key: "tr-finans", label: "Turkiye Finans Haberleri", description: "Turkiye finans ve ekonomi kaynaklari.", defaultSelected: true },
    ],
    configSchema: [
      {
        key: "focusKeywords",
        label: "Takip edilecek temalar",
        type: "textarea",
        placeholder: "Ornek: enflasyon, faiz, borsa, doviz, enerji",
        helpText: "Her satira bir tema veya varlik sinifi yaz.",
      },
    ],
    outputSchema: {
      findingKind: "MARKET_SIGNAL",
    },
    visibilityPackageKey: "PRO",
  },
  {
    id: "football-analysis",
    name: "Futbol Analiz Ajani",
    category: "sports",
    description: "Secilen liglerde haftanin maclarini sakatlik, form, rekabet ve puan durumu baglaminda analiz eder.",
    defaultPrompt:
      "Secilen ligler icin haftanin maclarini analiz et. Son 5 mac, sakat/cezali oyuncular, puan durumu, mac onemi ve derbi gibi rekabet unsurlarini birlikte yorumla.",
    defaultQueries: [
      "football fixtures injuries suspensions standings last 7 days",
      "match preview head to head injuries derby importance last 7 days",
      "team news suspensions standings match analysis this week",
    ],
    defaultTasks: [
      {
        key: "fixture-list",
        name: "Mac listesini cikar",
        category: "sports",
        description: "Secilen liglerdeki maclari listeler.",
        instruction: "Lig, takimlar ve mac tarihiyle mac listesini cikar.",
        defaultSelected: true,
      },
      {
        key: "tactical-analysis",
        name: "Detayli mac analizi yaz",
        category: "sports",
        description: "Form, eksik ve rekabet bilgisini yorumlar.",
        instruction: "Son 5 mac, eksikler, lig pozisyonu ve rekabet derecesine gore detayli analiz yaz.",
        defaultSelected: true,
      },
    ],
    taskBlueprints: [
      {
        key: "fixture-list",
        name: "Mac listesini cikar",
        category: "sports",
        description: "Secilen liglerdeki maclari listeler.",
        instruction: "Lig, takimlar ve mac tarihiyle mac listesini cikar.",
        defaultSelected: true,
      },
      {
        key: "tactical-analysis",
        name: "Detayli mac analizi yaz",
        category: "sports",
        description: "Form, eksik ve rekabet bilgisini yorumlar.",
        instruction: "Son 5 mac, eksikler, lig pozisyonu ve rekabet derecesine gore detayli analiz yaz.",
        defaultSelected: true,
      },
    ],
    defaultSchedule: {
      hour: 11,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [5, 6, 0],
    },
    defaultRule: {
      maxRunsPerDay: 2,
      maxRunsPerWeek: 10,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: [
      { key: "super-lig", label: "Super Lig", description: "Turkiye Super Lig maclari.", defaultSelected: true },
      { key: "premier-league", label: "Premier League", description: "Ingiltere Premier League maclari.", defaultSelected: true },
      { key: "la-liga", label: "La Liga", description: "Ispanya La Liga maclari." },
      { key: "serie-a", label: "Serie A", description: "Italya Serie A maclari." },
      { key: "bundesliga", label: "Bundesliga", description: "Almanya Bundesliga maclari." },
      { key: "champions-league", label: "Champions League", description: "UEFA Sampiyonlar Ligi maclari." },
    ],
    configSchema: [
      {
        key: "focusKeywords",
        label: "Takim veya mac odagi",
        type: "textarea",
        placeholder: "Ornek: Galatasaray, Arsenal, title race",
        helpText: "Her satira takim, rekabet veya odak yazabilirsin.",
      },
      {
        key: "matchWeek",
        label: "Hafta veya tur notu",
        type: "text",
        placeholder: "Ornek: 34. hafta",
        helpText: "Istersen belirli hafta veya tur bilgisini yaz.",
      },
    ],
    outputSchema: {
      findingKind: "NEWS",
    },
    visibilityPackageKey: "PREMIUM",
  },
  {
    id: "viral-content",
    name: "Viral Icerik Ajani",
    category: "social",
    description: "Turkiye ve globalde viral olan sosyal medya iceriklerini secilen platformlardan toplar.",
    defaultPrompt:
      "Secilen platformlarda son donemde viral olan icerikleri bul. Izlenme ve etkilesim sayisini one cikar, icerigin neden viral oldugunu kisa notlarla acikla.",
    defaultQueries: [
      "viral social media content youtube instagram tiktok reddit last 7 days",
      "most viewed social media posts shorts reels last 7 days",
      "viral videos high engagement twitter pinterest bluesky last 7 days",
    ],
    defaultTasks: [
      {
        key: "viral-list",
        name: "Viral icerik listesini cikar",
        category: "social",
        description: "En yuksek performansli icerikleri listeler.",
        instruction: "Link, platform ve etkilesim bilgisiyle icerik listesi cikar.",
        defaultSelected: true,
      },
      {
        key: "engagement-read",
        name: "Etkilesim yorumunu yaz",
        category: "social",
        description: "Neden one ciktigini analiz eder.",
        instruction: "Icerigin neden viral oldugunu ve hangi metrikle ayrildigini belirt.",
        defaultSelected: true,
      },
    ],
    taskBlueprints: [
      {
        key: "viral-list",
        name: "Viral icerik listesini cikar",
        category: "social",
        description: "En yuksek performansli icerikleri listeler.",
        instruction: "Link, platform ve etkilesim bilgisiyle icerik listesi cikar.",
        defaultSelected: true,
      },
      {
        key: "engagement-read",
        name: "Etkilesim yorumunu yaz",
        category: "social",
        description: "Neden one ciktigini analiz eder.",
        instruction: "Icerigin neden viral oldugunu ve hangi metrikle ayrildigini belirt.",
        defaultSelected: true,
      },
    ],
    defaultSchedule: {
      hour: 13,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 7,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    sourceCatalog: [
      { key: "youtube", label: "YouTube", description: "Uzun video icerikleri.", defaultSelected: true },
      { key: "youtube-shorts", label: "YouTube Shorts", description: "Kisa dikey video akisi.", defaultSelected: true },
      { key: "instagram-reels", label: "Instagram Reels", description: "Reels icerikleri.", defaultSelected: true },
      { key: "instagram-posts", label: "Instagram Posts", description: "Feed postlari." },
      { key: "tiktok", label: "TikTok", description: "TikTok viral icerikleri.", defaultSelected: true },
      { key: "x", label: "X / Twitter", description: "Yuksek etkilesimli gonderiler." },
      { key: "pinterest", label: "Pinterest", description: "Trend pin ve paylasimlar." },
      { key: "bluesky", label: "Bluesky", description: "Bluesky gundemi." },
      { key: "reddit", label: "Reddit", description: "Toplulukta trend olan link ve videolar." },
    ],
    configSchema: [
      {
        key: "focusKeywords",
        label: "Icerik konusu",
        type: "textarea",
        placeholder: "Ornek: AI tools, travel, comedy",
        helpText: "Her satira bir icerik konusu veya nishi yaz.",
        required: true,
      },
      {
        key: "minimumEngagement",
        label: "Minimum etkilesim notu",
        type: "text",
        placeholder: "Ornek: 10000+ etkileşim",
        helpText: "Istersen bir alt esik yazabilirsin.",
      },
    ],
    outputSchema: {
      findingKind: "NEWS",
      requiredMetadataFields: ["platform", "link", "izlenme", "etkilesim"],
      metadataLabels: {
        platform: "Platform",
        link: "Link",
        izlenme: "Izlenme",
        etkilesim: "Etkilesim",
      },
    },
    visibilityPackageKey: "BASIC",
  },
  {
    id: "stock-trade-coming-soon",
    name: "Borsa Trade Ajani",
    category: "trading",
    description: "Borsa entegrasyonlari, stop-loss ve manuel onay akisiyla ikinci fazda acilacak trade ajani.",
    defaultPrompt:
      "Bu ajan ikinci fazdadir. Trade otomasyonu ve stop-loss akis tasarimi tamamlandiginda aktive edilecektir.",
    defaultQueries: ["stock trading automation coming soon"],
    defaultTasks: [
      {
        key: "placeholder",
        name: "Yol haritasini goster",
        category: "trading",
        description: "Trade ajani placeholder gorevi.",
        instruction: "Kullaniciya bu ajanin yakinda acilacagini bildir.",
      },
    ],
    taskBlueprints: [
      {
        key: "placeholder",
        name: "Yol haritasini goster",
        category: "trading",
        description: "Trade ajani placeholder gorevi.",
        instruction: "Kullaniciya bu ajanin yakinda acilacagini bildir.",
      },
    ],
    defaultSchedule: {
      hour: 9,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 5,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    lifecycle: "COMING_SOON",
    isSelectable: false,
    outputSchema: {
      findingKind: "SYSTEM",
    },
    visibilityPackageKey: "PREMIUM",
  },
  {
    id: "crypto-trade-coming-soon",
    name: "Kripto Trade Ajani",
    category: "trading",
    description: "Borsa API entegrasyonlari ve stop-loss otomasyonu ikinci fazda acilacak trade ajani.",
    defaultPrompt:
      "Bu ajan ikinci fazdadir. Kripto trade otomasyonu, stop-loss ve cüzdan takibi tamamlandiginda aktive edilecektir.",
    defaultQueries: ["crypto trading automation coming soon"],
    defaultTasks: [
      {
        key: "placeholder",
        name: "Yol haritasini goster",
        category: "trading",
        description: "Trade ajani placeholder gorevi.",
        instruction: "Kullaniciya bu ajanin yakinda acilacagini bildir.",
      },
    ],
    taskBlueprints: [
      {
        key: "placeholder",
        name: "Yol haritasini goster",
        category: "trading",
        description: "Trade ajani placeholder gorevi.",
        instruction: "Kullaniciya bu ajanin yakinda acilacagini bildir.",
      },
    ],
    defaultSchedule: {
      hour: 9,
      minute: 0,
      timezone: "Europe/Istanbul",
      daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    },
    defaultRule: {
      maxRunsPerDay: 1,
      maxRunsPerWeek: 7,
      maxSourceAgeDays: 7,
      dedupeLookbackDays: 7,
      preventDuplicates: true,
    },
    suggestedProvider: "OPENROUTER",
    lifecycle: "COMING_SOON",
    isSelectable: false,
    outputSchema: {
      findingKind: "SYSTEM",
    },
    visibilityPackageKey: "PREMIUM",
  },
];

export function getTemplateSeed(templateId: string) {
  return AGENT_TEMPLATE_SEEDS.find((template) => template.id === templateId);
}

export function getPackageSeed(key: PlanPackageSeed["key"]) {
  return PACKAGE_SEEDS.find((item) => item.key === key);
}
